In [1]:
import tensorflow as tf
import numpy as np

/home/kiizuka/.venv/python3-tf/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/kiizuka/.venv/python3-tf/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/kiizuka/.venv/python3-tf/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/kiizuka/.venv/python3-tf/lib/python3.6/site-packages

In [10]:
input = np.array([
    [
        [230,230,230],[210,210,210],[190,190,190],[170,170,170],[150,150,150]
    ],
    [
        [230,230,230],[210,210,210],[190,190,190],[170,170,170],[150,150,150]
    ],
    [
        [230,230,230],[210,210,210],[190,190,190],[170,170,170],[150,150,150]
    ],
    [
        [230,230,230],[210,210,210],[190,190,190],[170,170,170],[150,150,150]
    ],
    [
        [230,230,230],[210,210,210],[190,190,190],[170,170,170],[150,150,150]
    ],
])

depth_radius = 2
bias = 1.0
alpha = 0.001 / 9.0
beta = 0.75

input_for_tf = np.zeros([1, input.shape[0], input.shape[1], input.shape[2]])
input_for_tf[0] = input
output2 = tf.nn.lrn(input_for_tf, depth_radius, bias=bias, alpha=alpha, beta=beta)
with tf.Session() as sess:
    out = sess.run(output2)
    print(type(out))
    print(out.shape)

<class 'numpy.ndarray'>
(1, 5, 5, 3)


## Check convolution using TensorFlow

In [9]:
conv_input = np.ones([1,  227, 227, 3])
weights = np.ones([11, 11, 3, 55])
stride = 4
padding = 0
output = tf.nn.conv2d(
    conv_input,
    filter=weights,
    strides=stride,
    padding='VALID',
    data_format='NHWC',
    dilations=[1, 1, 1, 1],
    name='test_conv'
)
with tf.Session() as sess:
    out = sess.run(output)
    print(type(out))
    print(out)

<class 'numpy.ndarray'>
[[[[363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   ...
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]]

  [[363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   ...
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]]

  [[363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   ...
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]]

  ...

  [[363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   ...
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]
   [363. 363. 363. ... 363. 363. 363.]

In [12]:
# params for lrn
depth_radius = 5
bias = 1.0
alpha = 0.0001
beta = 0.75

# params for max_pool
ksize = 3
padding = 0
strides = 2

pool1_input = np.ones([1, 96, 55, 55], dtype=np.float32)
# print(pool1_input.dtype)

relu = tf.nn.relu(pool1_input)
lrn = tf.nn.lrn(relu, depth_radius, bias=bias, alpha=alpha, beta=beta)
print(lrn.shape)

pool_test = np.ones([1, 55, 55, 96], dtype=np.float32)
pool_out = tf.nn.max_pool2d(pool_test, ksize=ksize, strides=strides, padding='VALID', data_format='NHWC', name='pool1')

with tf.compat.v1.Session() as sess:
    out = sess.run(pool_out)
    print(out.shape)

(1, 96, 55, 55)
(1, 27, 27, 96)
